'use client';
import {useEffect,useRef,useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import AdminIdentity from './AdminIdentity';
import {crmFields,crmKinds,crmLabels,emptyCrm,stages,type CrmKind,type CrmRecord} from '@/lib/cms/crm';
import type {CmsAccess} from '@/lib/cms/permissions';
import {saveCrm} from '@/app/admin/crm/actions';
export default function CrmManager({records,access}:{records:Record<CrmKind,CrmRecord[]>;access:CmsAccess}){
 const router=useRouter();const [kind,setKind]=useState<CrmKind>('contacts');const [draft,setDraft]=useState<CrmRecord|null>(null);const [dirty,setDirty]=useState(false);const [query,setQuery]=useState('');const [archived,setArchived]=useState(false);const [filter,setFilter]=useState('');const [message,setMessage]=useState('');const [pending,startTransition]=useTransition();
 const editorRef=useRef<HTMLElement>(null);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const editingId=draft?.id;
 useEffect(()=>{if(editingId!==undefined){editorRef.current?.scrollIntoView({block:'nearest'});editorRef.current?.querySelector<HTMLInputElement>('input')?.focus({preventScroll:true});}},[editingId]);
 const leave=()=>!dirty||window.confirm('Hay cambios sin guardar. ¿Descartarlos?');
 const edit=(record:CrmRecord)=>{if(!leave())return;setDraft({...record});setDirty(false);setMessage('');};
 const activeDeals=records.deals.filter(r=>!r.archived&&!['won','lost'].includes(String(r.stage)));
 const totals=Object.fromEntries(['MXN','USD','EUR'].map(currency=>[currency,activeDeals.filter(r=>r.currency===currency).reduce((sum,r)=>sum+Number(r.amount),0)]));
 const today=[new Date().getFullYear(),String(new Date().getMonth()+1).padStart(2,'0'),String(new Date().getDate()).padStart(2,'0')].join('-');
 const overdue=records.activities.filter(r=>!r.archived&&r.status==='pending'&&r.due_date&&String(r.due_date)<today).length;
 const visible=records[kind].filter(r=>r.archived===archived&&(!filter||r.stage===filter||r.status===filter)&&[r.name,r.email,r.owner,r.notes].some(v=>String(v??'').toLowerCase().includes(query.toLowerCase())));
 function update(key:string,value:string|boolean){setDraft(current=>current?{...current,[key]:value}:null);setDirty(true);}
 return <main className="cms-shell"><AdminIdentity active="crm" access={access} dirty={dirty} pending={pending}/>
 <section className="crm-heading"><div><h1>CRM</h1><p>Organiza contactos, oportunidades y próximos pasos.</p></div><button className="cms-publish" disabled={pending} onClick={()=>edit(emptyCrm(kind))}>{({companies:'Nueva empresa',contacts:'Nuevo contacto',deals:'Nueva oportunidad',activities:'Nueva actividad'})[kind]}</button></section>
 <section className="crm-summary" aria-label="Resumen CRM"><div><strong>{records.contacts.filter(r=>!r.archived).length}</strong> contactos activos</div><div><strong>{activeDeals.length}</strong> oportunidades abiertas</div><div><strong>{overdue}</strong> seguimientos vencidos</div><div>Valor abierto{Object.entries(totals).map(([currency,value])=><span key={currency}>{new Intl.NumberFormat('es-MX',{style:'currency',currency,currencyDisplay:'code'}).format(value)}</span>)}</div></section>
 <nav className="crm-tabs" aria-label="Entidades CRM">{crmKinds.map(k=><button key={k} aria-pressed={kind===k} disabled={pending} onClick={()=>{if(!leave())return;setKind(k);setDraft(null);setDirty(false);setFilter('');setQuery('');setMessage('');}}>{crmLabels[k]}</button>)}</nav>
 <div className="crm-filters"><label>Buscar<input value={query} onChange={e=>setQuery(e.target.value)} type="search" placeholder="Nombre, correo, responsable…"/></label><label>Vista<select value={String(archived)} onChange={e=>setArchived(e.target.value==='true')}><option value="false">Activos</option><option value="true">Archivados</option></select></label>{crmFields[kind].find(f=>['stage','status'].includes(f.key))&&<label>Estado / etapa<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">Todos</option>{Object.entries(crmFields[kind].find(f=>['stage','status'].includes(f.key))!.options!).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}</div>
 {kind==='deals'&&<div className="crm-pipeline">{Object.entries(stages).map(([stage,label])=><button key={stage} aria-pressed={filter===stage} onClick={()=>setFilter(filter===stage?'':stage)}>{label}<strong>{records.deals.filter(r=>!r.archived&&r.stage===stage).length}</strong></button>)}</div>}
 <p role="status" aria-live="polite" className="crm-message">{pending?'Guardando registro…':message||(dirty?'Cambios sin guardar.':'')}</p>
 <div className="crm-grid"><section aria-label={crmLabels[kind]}><p>{visible.length} registros · Hasta 1,000 recientes por categoría</p><div className="crm-records">{visible.map(record=><button key={record.id} disabled={pending} aria-pressed={draft?.id===record.id} onClick={()=>edit(record)}><strong>{record.name}</strong>{record.company_id&&<span>{records.companies.find(c=>c.id===record.company_id)?.name}</span>}{kind==='deals'&&<span>{new Intl.NumberFormat('es-MX',{style:'currency',currency:String(record.currency)}).format(Number(record.amount))} {record.currency}</span>}{kind==='activities'&&record.due_date&&<span className={record.status==='pending'&&String(record.due_date)<today?'crm-overdue':''}>Seguimiento: {String(record.due_date)}</span>}<span>{String(record.email||record.owner||'Sin responsable')}</span>{(record.stage||record.status)&&<small>{crmFields[kind].find(f=>f.key==='stage'||f.key==='status')?.options?.[String(record.stage||record.status)]}</small>}</button>)}{!visible.length&&<div className="cms-empty"><h2>{query||filter?'Sin coincidencias':'Empieza aquí'}</h2><p>{query||filter?'Prueba con otro nombre o limpia los filtros.':'Crea un registro para organizar tus relaciones y próximos pasos.'}</p>{(query||filter)&&<button className="cms-secondary" onClick={()=>{setQuery('');setFilter('');}}>Limpiar filtros</button>}</div>}</div></section>
 <section ref={editorRef} className="cms-edit-panel crm-editor">{draft?<form onSubmit={e=>{e.preventDefault();startTransition(async()=>{try{const result=await saveCrm(kind,draft.id,draft.version,draft);if(result.ok){setMessage('Registro guardado.');setDirty(false);setDraft(null);router.refresh();}else setMessage(result.error);}catch{setMessage('No se pudo confirmar el guardado. Tus cambios siguen aquí; recarga en otra pestaña para comprobar el registro antes de reintentar.');}});}}><h2>{draft.id?'Editar':'Crear'} · {crmLabels[kind]}</h2><fieldset disabled={pending} className="crm-fieldset"><label>Nombre / asunto *<input required maxLength={200} value={draft.name} onChange={e=>update('name',e.target.value)}/></label><div className="cms-field-pair">{crmFields[kind].map(field=><label key={field.key}>{field.label}{field.options||field.relation?<select value={String(draft[field.key]??'')} onChange={e=>update(field.key,e.target.value)}>{field.relation?<><option value="">Sin vincular</option>{records[field.relation].filter(r=>!r.archived||r.id===draft[field.key]).map(r=><option key={r.id} value={r.id}>{r.name}{r.archived?' (archivado)':''}</option>)}</>:Object.entries(field.options!).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select>:<input type={field.type||'text'} min={field.type==='number'?0:undefined} step={field.type==='number'?'.01':undefined} maxLength={field.type?undefined:200} value={String(draft[field.key]??'')} onChange={e=>update(field.key,e.target.value)}/>}</label>)}</div><label>Responsable (nombre o correo)<input maxLength={200} value={String(draft.owner)} onChange={e=>update('owner',e.target.value)}/></label><label>Notas<textarea rows={5} maxLength={10000} value={String(draft.notes)} onChange={e=>update('notes',e.target.value)}/></label><label className="crm-archive"><input type="checkbox" checked={draft.archived} onChange={e=>update('archived',e.target.checked)}/> Archivado</label>{message&&<p role="status" className="cms-warning">{message}</p>}<div className="crm-save-bar"><button className="cms-publish" disabled={!dirty&&!!draft.id} type="submit">{pending?'Guardando…':'Guardar registro'}</button><button type="button" className="cms-secondary" onClick={()=>{if(leave()){setDraft(null);setDirty(false);setMessage('');}}}>Cerrar editor</button></div></fieldset><p>Los registros archivados conservan sus relaciones. Las actividades de correo registran el seguimiento; el envío se realiza fuera del CRM.</p></form>:<><h2>Gestiona tus relaciones</h2><p>Selecciona un registro para editar o crea uno nuevo. Empieza por una empresa y sus contactos; después vincula oportunidades y actividades.</p></>}</section></div>
 </main>;
}
