'use client';
import {useAdminLanguage} from '@/components/admin/AdminLanguage';

import {useEffect,useRef,useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import AdminIdentity from './AdminIdentity';
import {crmFields,crmKinds,crmLabels,emptyCrm,stages,type CrmKind,type CrmRecord} from '@/lib/cms/crm';
import type {CmsAccess} from '@/lib/cms/permissions';
import CrmKanban from './CrmKanban';
import {saveCrm,moveCrmDeal} from '@/app/admin/crm/actions';
export default function CrmManager({records,access}:{records:Record<CrmKind,CrmRecord[]>;access:CmsAccess}){
 const {t,locale}=useAdminLanguage();

 const router=useRouter();const [kind,setKind]=useState<CrmKind>('contacts');const [draft,setDraft]=useState<CrmRecord|null>(null);const [dirty,setDirty]=useState(false);const [query,setQuery]=useState('');const [archived,setArchived]=useState(false);const [filter,setFilter]=useState('');const [message,setMessage]=useState('');const [pending,startTransition]=useTransition();
 const [view,setView]=useState<'list'|'kanban'>('list');
 const [moving,setMoving]=useState(false);
 const moveLock=useRef(false);
 const [stageUpdates,setStageUpdates]=useState<Record<string,{stage:string;version:number}>>({});
 const deals=records.deals.map(record=>stageUpdates[record.id]&&stageUpdates[record.id].version>record.version?{...record,...stageUpdates[record.id]}:record);
 async function moveDeal(record:CrmRecord,stage:string){
  if(moveLock.current||dirty||pending||record.stage===stage)return;
  moveLock.current=true;setMoving(true);setMessage('');
  try{const result=await moveCrmDeal(record.id,record.version,stage);if(result.ok){setStageUpdates(current=>({...current,[record.id]:{stage:result.record.stage,version:result.record.version}}));if(draft?.id===record.id)setDraft(current=>current?{...current,stage:result.record.stage,version:result.record.version}:null);setMessage('Etapa actualizada.');router.refresh();}else {setMessage(result.error);router.refresh();}}catch{setMessage('No se pudo mover la oportunidad. La etapa original se conserva.');}finally{moveLock.current=false;setMoving(false);}
 }
 const editorRef=useRef<HTMLElement>(null);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const editingId=draft?.id;
 useEffect(()=>{if(editingId!==undefined){editorRef.current?.scrollIntoView({block:'nearest'});editorRef.current?.querySelector<HTMLInputElement>('input')?.focus({preventScroll:true});}},[editingId]);
 const leave=()=>!dirty||window.confirm(t("Hay cambios sin guardar. ¿Descartarlos?"));
 const edit=(record:CrmRecord)=>{if(!leave())return;setDraft({...record});setDirty(false);setMessage('');};
 const activeDeals=deals.filter(r=>!r.archived&&!['won','lost'].includes(String(r.stage)));
 const totals=Object.fromEntries(['MXN','USD','EUR'].map(currency=>[currency,activeDeals.filter(r=>r.currency===currency).reduce((sum,r)=>sum+Number(r.amount),0)]));
 const today=[new Date().getFullYear(),String(new Date().getMonth()+1).padStart(2,'0'),String(new Date().getDate()).padStart(2,'0')].join('-');
 const overdue=records.activities.filter(r=>!r.archived&&r.status==='pending'&&r.due_date&&String(r.due_date)<today).length;
 const visible=(kind==='deals'?deals:records[kind]).filter(r=>r.archived===archived&&(!filter||r.stage===filter||r.status===filter)&&[r.name,r.email,r.owner,r.notes].some(v=>String(v??'').toLowerCase().includes(query.toLowerCase())));
 function update(key:string,value:string|boolean){setDraft(current=>current?{...current,[key]:value}:null);setDirty(true);}
 return <main className="cms-shell"><AdminIdentity active="crm" access={access} dirty={dirty} pending={pending||moving}/>
 <section className="crm-heading"><div><h1>CRM</h1><p>{t("Organiza contactos, oportunidades y próximos pasos.")}</p></div><button className="cms-publish" disabled={pending||moving} onClick={()=>edit(emptyCrm(kind))}>{({companies:t("Nueva empresa"),contacts:t("Nuevo contacto"),deals:t("Nueva oportunidad"),activities:t("Nueva actividad")})[kind]}</button></section>
 <section className="crm-summary" aria-label={t("Resumen CRM")}><div><strong>{records.contacts.filter(r=>!r.archived).length}</strong> {t(" contactos activos")}</div><div><strong>{activeDeals.length}</strong> {t(" oportunidades abiertas")}</div><div><strong>{overdue}</strong> {t(" seguimientos vencidos")}</div><div>{t("Valor abierto")}{Object.entries(totals).map(([currency,value])=><span key={currency}>{new Intl.NumberFormat(locale,{style:'currency',currency,currencyDisplay:'code'}).format(value)}</span>)}</div></section>
 <nav className="crm-tabs" aria-label={t("Entidades CRM")}>{crmKinds.map(k=><button key={k} aria-pressed={kind===k} disabled={pending||moving} onClick={()=>{if(!leave())return;setKind(k);setDraft(null);setDirty(false);setFilter('');setQuery('');setMessage('');}}>{t(crmLabels[k])}</button>)}</nav>
 <div className="crm-filters"><label>{t("Buscar")}<input value={query} onChange={e=>setQuery(e.target.value)} type="search" placeholder={t("Nombre, correo, responsable…")}/></label><label>{t("Vista")}<select value={String(archived)} onChange={e=>setArchived(e.target.value==='true')}><option value="false">{t("Activos")}</option><option value="true">{t("Archivados")}</option></select></label>{crmFields[kind].find(f=>['stage','status'].includes(f.key))&&<label>{t("Estado / etapa")}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">{t("Todos")}</option>{Object.entries(crmFields[kind].find(f=>['stage','status'].includes(f.key))!.options!).map(([value,label])=><option key={value} value={value}>{t(label)}</option>)}</select></label>}</div>
 {kind==='deals'&&<div className="crm-view-toggle" role="group" aria-label={t('Vista')}><button className="cms-secondary" aria-pressed={view==='list'} onClick={()=>setView('list')}>{t('Lista')}</button><button className="cms-secondary" aria-pressed={view==='kanban'} onClick={()=>{setView('kanban');setFilter('');}}>{t('Tablero Kanban')}</button></div>}
 {kind==='deals'&&view==='list'&&<div className="crm-pipeline">{Object.entries(stages).map(([stage,label])=><button key={stage} aria-pressed={filter===stage} onClick={()=>setFilter(filter===stage?'':stage)}>{t(label)}<strong>{deals.filter(r=>!r.archived&&r.stage===stage).length}</strong></button>)}</div>}
 <p role="status" aria-live="polite" className="crm-message">{moving?t("Moviendo oportunidad…"):pending?t("Guardando registro…"):t(message)||(dirty?t("Cambios sin guardar."):'')}</p>
 {kind==='deals'&&view==='kanban'&&<CrmKanban records={visible} companies={records.companies} disabled={dirty||pending||moving||archived} moving={moving} onMove={moveDeal} onEdit={edit}/>}
 <div className={kind==='deals'&&view==='kanban'?'crm-grid crm-board-editor':'crm-grid'}><section hidden={kind==='deals'&&view==='kanban'} aria-label={t(crmLabels[kind])}><p>{visible.length} {t(" registros · Hasta 1,000 recientes por categoría")}</p><div className="crm-records">{visible.map(record=><button key={record.id} disabled={pending||moving} aria-pressed={draft?.id===record.id} onClick={()=>edit(record)}><strong>{record.name}</strong>{record.company_id&&<span>{records.companies.find(c=>c.id===record.company_id)?.name}</span>}{kind==='deals'&&<span>{new Intl.NumberFormat(locale,{style:'currency',currency:String(record.currency)}).format(Number(record.amount))} {record.currency}</span>}{kind==='activities'&&record.due_date&&<span className={record.status==='pending'&&String(record.due_date)<today?'crm-overdue':''}>{t("Seguimiento: ")}{String(record.due_date)}</span>}<span>{String(record.email||record.owner||t("Sin responsable"))}</span>{(record.stage||record.status)&&<small>{t(crmFields[kind].find(f=>f.key==='stage'||f.key==='status')?.options?.[String(record.stage||record.status)]??'')}</small>}</button>)}{!visible.length&&<div className="cms-empty"><h2>{query||filter?t("Sin coincidencias"):t("Empieza aquí")}</h2><p>{query||filter?t("Prueba con otro nombre o limpia los filtros."):t("Crea un registro para organizar tus relaciones y próximos pasos.")}</p>{(query||filter)&&<button className="cms-secondary" onClick={()=>{setQuery('');setFilter('');}}>{t("Limpiar filtros")}</button>}</div>}</div></section>
 <section ref={editorRef} className="cms-edit-panel crm-editor">{draft?<form onSubmit={e=>{e.preventDefault();startTransition(async()=>{try{const result=await saveCrm(kind,draft.id,draft.version,draft);if(result.ok){setMessage('Registro guardado.');setDirty(false);setDraft(null);router.refresh();}else setMessage(result.error);}catch{setMessage('No se pudo confirmar el guardado. Tus cambios siguen aquí; recarga en otra pestaña para comprobar el registro antes de reintentar.');}});}}><h2>{draft.id?t("Editar"):t("Crear")} · {t(crmLabels[kind])}</h2><fieldset disabled={pending||moving} className="crm-fieldset"><label>{t("Nombre / asunto *")}<input required maxLength={200} value={draft.name} onChange={e=>update('name',e.target.value)}/></label><div className="cms-field-pair">{crmFields[kind].map(field=><label key={field.key}>{t(field.label)}{field.options||field.relation?<select value={String(draft[field.key]??'')} onChange={e=>update(field.key,e.target.value)}>{field.relation?<><option value="">{t("Sin vincular")}</option>{records[field.relation].filter(r=>!r.archived||r.id===draft[field.key]).map(r=><option key={r.id} value={r.id}>{r.name}{r.archived?t(' (archivado)'):''}</option>)}</>:Object.entries(field.options!).map(([v,label])=><option key={v} value={v}>{t(label)}</option>)}</select>:<input type={field.type||'text'} min={field.type==='number'?0:undefined} step={field.type==='number'?'.01':undefined} maxLength={field.type?undefined:200} value={String(draft[field.key]??'')} onChange={e=>update(field.key,e.target.value)}/>}</label>)}</div><label>{t("Responsable (nombre o correo)")}<input maxLength={200} value={String(draft.owner)} onChange={e=>update('owner',e.target.value)}/></label><label>{t("Notas")}<textarea rows={5} maxLength={10000} value={String(draft.notes)} onChange={e=>update('notes',e.target.value)}/></label><label className="crm-archive"><input type="checkbox" checked={draft.archived} onChange={e=>update('archived',e.target.checked)}/> {t(" Archivado")}</label>{message&&<p role="status" className="cms-warning">{t(message)}</p>}<div className="crm-save-bar"><button className="cms-publish" disabled={!dirty&&!!draft.id} type="submit">{pending?t("Guardando…"):t("Guardar registro")}</button><button type="button" className="cms-secondary" onClick={()=>{if(leave()){setDraft(null);setDirty(false);setMessage('');}}}>{t("Cerrar editor")}</button></div></fieldset><p>{t("Los registros archivados conservan sus relaciones. Las actividades de correo registran el seguimiento; el envío se realiza fuera del CRM.")}</p></form>:<><h2>{t("Gestiona tus relaciones")}</h2><p>{t("Selecciona un registro para editar o crea uno nuevo. Empieza por una empresa y sus contactos; después vincula oportunidades y actividades.")}</p></>}</section></div>
 </main>;
}
