'use client';
import {useEffect,useState,useTransition} from 'react';
import AdminIdentity from './AdminIdentity';
import {cmsModules,moduleLabels,type CmsUser,type CmsModule,type CmsAccess} from '@/lib/cms/permissions';
import {setUserPermissions} from '@/app/admin/users/actions';
export default function UsersManager({initialUsers,access}:{initialUsers:CmsUser[];access:CmsAccess}){
 const [users,setUsers]=useState(initialUsers),[search,setSearch]=useState(''),[selected,setSelected]=useState<CmsUser|null>(null),[modules,setModules]=useState<CmsModule[]>([]),[confirm,setConfirm]=useState(false),[message,setMessage]=useState(''),[pending,start]=useTransition();
 const dirty=!!selected&&!selected.admin&&JSON.stringify([...selected.modules].sort())!==JSON.stringify([...modules].sort());
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[dirty]);
 function choose(user:CmsUser){if(dirty&&!window.confirm('¿Descartar los cambios de permisos sin guardar?'))return;setSelected(user);setModules(user.admin?[...cmsModules]:user.modules);setConfirm(false);setMessage('');}
 function save(){if(!selected)return;start(async()=>{try{const result=await setUserPermissions(selected.id,modules,selected.modules);if(!result.ok){setMessage(result.error);return;}const changed={...selected,modules};setSelected(changed);setUsers(list=>list.map(u=>u.id===changed.id?changed:u));setConfirm(false);setMessage('Permisos actualizados. Se aplican en la siguiente operación del usuario.');}catch{setMessage('No se pudo confirmar el cambio. Recarga y comprueba los permisos antes de reintentar.');}});}
 const matches=users.filter(u=>(u.email??'').toLowerCase().includes(search.toLowerCase()));
 return <main className="cms-shell"><AdminIdentity active="users" access={access} dirty={dirty} pending={pending}/><header><div><h1>Usuarios y permisos</h1><p>Decide quién puede editar y publicar en cada módulo.</p></div></header><p className="cms-help">Se muestran las cuentas existentes en Supabase Auth. El alta de nuevas cuentas se realiza en Supabase; este formulario administra su acceso al CMS.</p><p className="cms-status" role="status">{pending?'Guardando permisos…':message}</p>
 <div className="cms-collection"><aside className="cms-entry-list"><label>Buscar por correo<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Correo del usuario"/></label><p>{matches.length} {matches.length===1?'cuenta':'cuentas'}</p><ul>{matches.map(user=><li key={user.id}><button className="cms-secondary" disabled={pending} aria-current={selected?.id===user.id?'true':undefined} onClick={()=>choose(user)}><strong>{user.email??'Sin correo'}</strong><small>{user.admin?'Administrador general':user.modules.length?user.modules.map(m=>moduleLabels[m]).join(' · '):'Sin acceso al CMS'}</small></button></li>)}</ul>{!matches.length&&<p>No hay cuentas que coincidan.</p>}</aside>
 <section className="cms-edit-panel">{selected?<><h2 className="cms-user-email">{selected.email??'Cuenta sin correo'}</h2><p className="cms-help">{selected.confirmed?'Correo confirmado':'Correo pendiente de confirmación'}</p>{selected.admin?<p className="cms-warning">Administrador general. Tiene acceso a todos los módulos y a la gestión de usuarios. Esta pantalla conserva sus permisos.</p>:<><fieldset disabled={pending} className="cms-permission-options"><legend>Permisos de gestión</legend>{cmsModules.map(module=><label key={module}><input type="checkbox" checked={modules.includes(module)} onChange={e=>{setModules(current=>e.target.checked?[...current,module]:current.filter(m=>m!==module));setConfirm(false);setMessage('');}}/><span><strong>{moduleLabels[module]}</strong><small>{module==='crm'?'Gestionar empresas, contactos, oportunidades y actividades.':'Editar, guardar y publicar contenido.'}</small></span></label>)}</fieldset><p className="cms-help">Si desmarcas todos los módulos, la cuenta conserva su inicio de sesión pero pierde acceso al CMS. La biblioteca de imágenes es compartida entre los módulos autorizados.</p><button disabled={!dirty||pending} onClick={()=>setConfirm(true)}>Revisar cambios</button>{confirm&&<div className="cms-warning"><p>Guardar para <strong>{selected.email}</strong>: {modules.length?modules.map(m=>moduleLabels[m]).join(', '):'sin acceso a los módulos'}.</p><button disabled={pending} onClick={save}>Confirmar permisos</button> <button className="cms-secondary" disabled={pending} onClick={()=>setConfirm(false)}>Cancelar</button></div>}</>}</>:<><h2>Selecciona una cuenta</h2><p className="cms-help">Busca un usuario y asigna los módulos que podrá gestionar. Solo los administradores generales pueden modificar estos permisos.</p></>}</section></div></main>;
}
