/* CMS media are validated local images or public Supabase storage URLs. */
/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import BlogBody from '@/components/admin/BlogBody';
import type {BlogPost} from '@/lib/blog/posts';
export const blogPath=(slug:string)=>`/blog/${encodeURIComponent(slug)}`;
const date=(value:string)=>new Intl.DateTimeFormat('en',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(value));
export function PostMeta({post,preview=false}:{post:BlogPost;preview?:boolean}){return <p className="blog-meta">{post.content.author&&<span>{post.content.author}</span>}{preview?<span>Draft preview</span>:<time dateTime={post.published_at}>{date(post.published_at)}</time>}<span>{Math.max(1,Math.ceil(post.content.body.trim().split(/\s+/u).length/200))} min read</span></p>;}
function Cover({post,featured=false}:{post:BlogPost;featured?:boolean}){return post.content.image?<img className="blog-cover" src={post.content.image} alt={post.content.alt} loading={featured?'eager':'lazy'} fetchPriority={featured?'high':'auto'}/>:<div className="blog-cover blog-cover-empty" aria-hidden="true"><span>cambio<br/>natural</span></div>;}
export function PostCard({post,featured=false,href=blogPath(post.slug)}:{post:BlogPost;featured?:boolean;href?:string}){return <article className={featured?'blog-feature':'blog-card'}><Link href={href} className="blog-image-link" tabIndex={-1} aria-hidden="true"><Cover post={post} featured={featured}/></Link><div className="blog-card-copy"><PostMeta post={post}/><h2><Link href={href}>{post.content.title}</Link></h2>{post.content.summary&&<p className="blog-summary">{post.content.summary}</p>}<Link href={href} className="blog-read" aria-label={`Read ${post.content.title}`}>Read story <span aria-hidden="true">↗</span></Link></div></article>;}
export function BlogIndex({posts,total,page=1,postHref=blogPath}:{posts:BlogPost[];total:number;page?:number;postHref?:(slug:string)=>string}){
 const featured=page===1?posts[0]:null;const remaining=featured?posts.slice(1):posts;const pages=Math.ceil(total/9);
 return <main id="blog-main"><header className="blog-masthead"><div className="blog-wrap"><h1>Blog<span aria-hidden="true">.</span></h1><p>Ideas, stories and conversations<br className="blog-desktop-break"/> for a healthier planet.</p></div></header><div className="blog-wrap blog-index-content">
 {featured&&<section aria-label="Latest story"><PostCard post={featured} featured href={postHref(featured.slug)}/></section>}
 {remaining.length>0&&<section className="blog-archive" aria-labelledby="archive-title"><div className="blog-section-title"><h2 id="archive-title">{page===1?'More stories':'Stories'}</h2><span>{total} {total===1?'story':'stories'}</span></div><div className="blog-grid">{remaining.map(post=><PostCard key={post.id} post={post} href={postHref(post.slug)}/>)}</div></section>}
 {!posts.length&&<section className="blog-empty"><h2>A space for what comes next.</h2><p>Our first stories are on their way. In the meantime, explore the conversations in our Media Club.</p><Link href="/media-club" className="blog-button">Explore the Media Club</Link></section>}
 {pages>1&&<nav className="blog-pagination" aria-label="Blog pages">{page>1?<Link href={page===2?'/blog':`/blog?page=${page-1}`}>← Newer stories</Link>:<span/>}<span>Page {page} of {pages}</span>{page<pages?<Link href={`/blog?page=${page+1}`}>Older stories →</Link>:<span/>}</nav>}
 </div><BlogClose/></main>;
}
export function BlogArticle({post,related=[],preview=false}:{post:BlogPost;related?:BlogPost[];preview?:boolean}){return <main id="blog-main"><article><header className="blog-article-header blog-wrap"><Link href="/blog" className="blog-back">← All stories</Link><PostMeta post={post} preview={preview}/><h1>{post.content.title}</h1>{post.content.summary&&<p className="blog-deck">{post.content.summary}</p>}</header>{post.content.image&&<figure className="blog-article-cover blog-wrap"><Cover post={post} featured/></figure>}<div className="blog-reading"><BlogBody body={post.content.body} richText={post.content.richText}/><div className="blog-article-end"><Link href="/blog">← Back to all stories</Link><a href="#blog-main">Back to top ↑</a></div></div></article>{related.length>0&&<section className="blog-wrap blog-related" aria-labelledby="related-title"><div className="blog-section-title"><h2 id="related-title">Keep exploring</h2></div><div className="blog-grid">{related.map(item=><PostCard key={item.id} post={item}/>)}</div></section>}<BlogClose/></main>;}
function BlogClose(){return <aside className="blog-close"><div className="blog-wrap"><h2>Keep the conversation going.</h2><div><p>Read, listen and exchange ideas with the Media Club.</p><Link href="/media-club" className="blog-button">Meet the Media Club <span aria-hidden="true">↗</span></Link></div></div></aside>;}
